import React, { useState, useMemo } from 'react';
import { Upload, FileText, TrendingUp, TrendingDown, Lightbulb, Target, PieChart as PieIcon, Activity, AlertCircle, Filter, RefreshCw, X } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, LineChart, Line, PieChart, Pie, Cell, Legend } from 'recharts';
import { analyzeSalesData } from '../services/geminiService';
import { AnalyticsReport } from '../types';

interface AnalyticsDashboardProps {
  onDataLoaded: (data: string) => void;
  isDarkMode: boolean;
}

const COLORS = ['#4f46e5', '#8b5cf6', '#ec4899', '#f59e0b', '#10b981'];

export const AnalyticsDashboard: React.FC<AnalyticsDashboardProps> = ({ onDataLoaded, isDarkMode }) => {
  const [data, setData] = useState<AnalyticsReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<'daily' | 'weekly' | 'monthly'>('monthly');
  const [selectedPerson, setSelectedPerson] = useState<string | null>(null);
  const [fileName, setFileName] = useState<string>('');
  const [selectedRow, setSelectedRow] = useState<any | null>(null);

  // Filtering State
  const [parsedRows, setParsedRows] = useState<any[]>([]);
  const [headers, setHeaders] = useState<string[]>([]);
  const [activeFilters, setActiveFilters] = useState<{[key: string]: string}>({});
  const [availableFilters, setAvailableFilters] = useState<{[key: string]: string[]}>({});

  const parseData = (text: string) => {
    try {
        let rows: any[] = [];
        let detectedHeaders: string[] = [];

        const trimmed = text.trim();
        if (trimmed.startsWith('[') || trimmed.startsWith('{')) {
            // Try JSON
            try {
                const json = JSON.parse(trimmed);
                if (Array.isArray(json)) {
                    rows = json;
                } else if (typeof json === 'object') {
                    // Try to find an array property
                    const arrayProp = Object.values(json).find(v => Array.isArray(v));
                    if (arrayProp && Array.isArray(arrayProp)) rows = arrayProp;
                }
            } catch (e) { console.error("JSON parse failed", e); }
        }
        
        if (rows.length === 0) {
            // Try CSV
            const lines = trimmed.split('\n');
            if (lines.length > 1) {
                detectedHeaders = lines[0].split(',').map(h => h.trim().replace(/^"|"$/g, ''));
                for (let i = 1; i < lines.length; i++) {
                    const line = lines[i].trim();
                    if (!line) continue;
                    // Handle quoted commas purely (simple regex) or simple split
                    const values = line.split(/,(?=(?:(?:[^"]*"){2})*[^"]*$)/).map(v => v.trim().replace(/^"|"$/g, ''));
                    const row: any = {};
                    detectedHeaders.forEach((h, idx) => {
                        row[h] = values[idx];
                    });
                    rows.push(row);
                }
            }
        } else {
            // If JSON, extract headers from first object
            if (rows.length > 0) {
                detectedHeaders = Object.keys(rows[0]);
            }
        }

        setHeaders(detectedHeaders);
        setParsedRows(rows);
        generateFilterOptions(rows, detectedHeaders);
        
        // Automatically generate KPIs based on columns
        generateAutomaticKPIs(rows, detectedHeaders);
        
        return rows;
    } catch (e) {
        console.error("Parsing Error", e);
        return [];
    }
  };

  const generateAutomaticKPIs = (rows: any[], headers: string[]) => {
    if (rows.length === 0) return;
    
    const kpis: any[] = [];
    
    // Total rows
    kpis.push({
      label: "Total Records",
      value: rows.length,
      change: "records"
    });
    
    // Try to find numeric columns for additional KPIs
    headers.forEach(header => {
      // Check if this column contains mostly numeric values
      const numericValues = rows
        .map(row => row[header])
        .filter(val => !isNaN(parseFloat(String(val))) && isFinite(parseFloat(String(val))));
      
      if (numericValues.length > 0) {
        const sum = numericValues.reduce((acc, val) => acc + parseFloat(String(val)), 0);
        const avg = sum / numericValues.length;
        const max = Math.max(...numericValues.map(val => parseFloat(String(val))));
        const min = Math.min(...numericValues.map(val => parseFloat(String(val))));
        
        kpis.push({
          label: `${header} (Avg)`,
          value: avg.toFixed(2),
          change: "average"
        });
        
        kpis.push({
          label: `${header} (Sum)`,
          value: sum.toFixed(2),
          change: "total"
        });
      }
    });
    
    // Update the data state with automatic KPIs if no KPIs were generated by AI
    if (data && data.kpis.length === 0) {
      setData({
        ...data,
        kpis: kpis.slice(0, 4) // Limit to 4 KPIs to fit the grid
      });
    }
  };

  const generateFilterOptions = (rows: any[], cols: string[]) => {
      const filters: {[key: string]: Set<string>} = {};
      
      cols.forEach(col => {
          // Heuristic: Only columns with text values and cardinality < 50 are likely good filters
          // Or if user specifically mentioned names/locations, usually those are strings.
          const uniqueValues = new Set<string>();
          let isStringColumn = true;

          for (const row of rows) {
             const val = row[col];
             if (typeof val !== 'string' && typeof val !== 'number') continue;
             uniqueValues.add(String(val));
             if (uniqueValues.size > 100) break; // Limit cardinality
          }

          if (uniqueValues.size > 0 && uniqueValues.size < 100) {
             filters[col] = uniqueValues;
          }
      });

      const finalOptions: {[key: string]: string[]} = {};
      Object.keys(filters).forEach(k => {
          finalOptions[k] = Array.from(filters[k]).sort();
      });
      setAvailableFilters(finalOptions);
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    setLoading(true);
    setActiveFilters({}); // Reset filters on new upload

    const reader = new FileReader();
    reader.onload = async (event) => {
      const text = event.target?.result as string;
      onDataLoaded(text); // Store raw text for Chat
      
      // Parse for local filtering
      parseData(text);

      // Analyze Full Dataset
      try {
        const report = await analyzeSalesData(text);
        setData(report);
      } catch (err) {
        console.error(err);
        alert("Error analyzing data. Please ensure it is a valid CSV/JSON text file.");
      } finally {
        setLoading(false);
      }
    };
    reader.readAsText(file);
  };

  const handleFilterChange = (col: string, val: string) => {
      const newFilters = { ...activeFilters };
      if (val === "ALL") {
          delete newFilters[col];
      } else {
          newFilters[col] = val;
      }
      setActiveFilters(newFilters);
      applyAnalysisOnFilteredData(newFilters);
  };

  const applyAnalysisOnFilteredData = async (currentFilters: {[key: string]: string}) => {
      setLoading(true);
      try {
          // Filter rows
          const filtered = parsedRows.filter(row => {
              return Object.entries(currentFilters).every(([key, filterVal]) => {
                  return String(row[key]) === filterVal;
              });
          });

          // Convert back to CSV string for AI
          if (filtered.length === 0) {
              alert("No data matches these filters.");
              setLoading(false);
              return;
          }

          let dataString = "";
          // If headers exist, map nicely
          if (headers.length > 0) {
              dataString += headers.join(",") + "\n";
              filtered.forEach(row => {
                  dataString += headers.map(h => `"${row[h] || ''}"`).join(",") + "\n";
              });
          } else {
             dataString = JSON.stringify(filtered);
          }

          const report = await analyzeSalesData(dataString);
          setData(report);

      } catch (e) {
          console.error("Filter analysis failed", e);
      } finally {
          setLoading(false);
      }
  };

  const clearFilters = () => {
      setActiveFilters({});
      // Re-run analysis on full parsedRows
      applyAnalysisOnFilteredData({});
  };

  const analyzeSingleRow = async (row: any) => {
      setSelectedRow(row);
      setLoading(true);
      
      try {
          // Convert single row to CSV format for analysis
          let dataString = "";
          if (headers.length > 0) {
              dataString += headers.join(",") + "\n";
              dataString += headers.map(h => `"${row[h] || ''}"`).join(",") + "\n";
          } else {
              dataString = JSON.stringify([row]);
          }
          
          const report = await analyzeSalesData(dataString);
          
          // Show a modal or alert with the analysis
          alert(`Analysis for selected row:\n\n${report.dailySummary || report.monthlySummary || 'No summary available'}`);
      } catch (e) {
          console.error("Single row analysis failed", e);
          alert("Failed to analyze this row. Please try again.");
      } finally {
          setLoading(false);
      }
  };

  return (
    <div className="p-4 md:p-6 max-w-[1600px] mx-auto space-y-6 md:space-y-8 animate-fade-in">
      {/* Header */}
      <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white dark:bg-slate-900 p-6 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-800">
        <div>
            <h2 className="text-2xl md:text-3xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <Activity className="text-indigo-600" />
                Data Intelligence
            </h2>
            <p className="text-sm md:text-base text-slate-500 dark:text-slate-400 mt-1">Upload raw data (CSV/JSON) to generate boardroom-ready insights.</p>
        </div>
        <div className="w-full md:w-auto flex flex-col sm:flex-row items-stretch sm:items-center gap-4">
            {fileName && (
              <span className="text-sm text-slate-500 dark:text-slate-300 bg-slate-100 dark:bg-slate-800 px-3 py-2 rounded-lg flex items-center justify-center gap-2">
                <FileText size={14}/> 
                <span className="truncate max-w-[150px]">{fileName}</span>
              </span>
            )}
            <label className="cursor-pointer bg-indigo-600 text-white px-5 py-3 rounded-xl hover:bg-indigo-700 transition flex items-center justify-center gap-2 shadow-lg shadow-indigo-200 dark:shadow-none font-semibold">
                <Upload className="w-4 h-4" />
                Upload Data
                <input type="file" className="hidden" accept=".csv,.json,.txt" onChange={handleFileUpload} />
            </label>
        </div>
      </header>

      {/* Loading State */}
      {loading && (
        <div className="flex flex-col items-center justify-center h-96 space-y-6 bg-white dark:bg-slate-900 rounded-3xl border border-slate-100 dark:border-slate-800">
            <div className="relative">
                <div className="w-16 h-16 border-4 border-indigo-200 dark:border-indigo-900 border-t-indigo-600 rounded-full animate-spin"></div>
                <div className="absolute inset-0 flex items-center justify-center">
                    <Activity className="w-6 h-6 text-indigo-600" />
                </div>
            </div>
            <div className="text-center">
                <p className="text-lg font-bold text-slate-800 dark:text-white">Analyzing Dataset...</p>
                <p className="text-slate-500 dark:text-slate-400 text-sm mt-1">AI is processing your specific view.</p>
            </div>
        </div>
      )}

      {/* Filters Bar */}
      {!loading && fileName && Object.keys(availableFilters).length > 0 && (
          <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-100 dark:border-slate-800 flex flex-col sm:flex-row gap-4 items-start sm:items-center overflow-x-auto">
              <div className="flex items-center gap-2 text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wide flex-shrink-0">
                  <Filter size={16} /> Filters:
              </div>
              <div className="flex gap-3 flex-wrap flex-1">
                  {Object.entries(availableFilters).map(([col, options]) => (
                      <div key={col} className="relative group">
                          <select 
                              value={activeFilters[col] || "ALL"}
                              onChange={(e) => handleFilterChange(col, e.target.value)}
                              className="appearance-none bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 text-xs font-medium py-2 pl-3 pr-8 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500 cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors min-w-[120px]"
                          >
                              <option value="ALL">{col}: All</option>
                              {options.map(opt => (
                                  <option key={opt} value={opt}>{opt}</option>
                              ))}
                          </select>
                          <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none">
                              <svg className="w-3 h-3 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path></svg>
                          </div>
                      </div>
                  ))}
                  {Object.keys(activeFilters).length > 0 && (
                      <button 
                        onClick={clearFilters}
                        className="flex items-center gap-1 text-xs text-red-500 hover:text-red-600 font-bold px-3 py-2 bg-red-50 dark:bg-red-900/10 rounded-lg transition-colors"
                      >
                          <X size={14} /> Clear
                      </button>
                  )}
              </div>
          </div>
      )}

      {/* Empty State */}
      {!loading && !data && (
        <div className="border-2 border-dashed border-slate-300 dark:border-slate-700 rounded-3xl h-96 flex flex-col items-center justify-center text-slate-400 dark:text-slate-500 bg-slate-50 dark:bg-slate-900/50 mx-2 group hover:bg-slate-100 dark:hover:bg-slate-800/50 transition-colors">
            <div className="w-20 h-20 bg-white dark:bg-slate-800 rounded-2xl flex items-center justify-center shadow-sm mb-4 group-hover:scale-110 transition-transform duration-300">
                <BarChart2Icon className="w-10 h-10 text-indigo-500/50" />
            </div>
            <p className="text-lg font-medium text-slate-600 dark:text-slate-300">No Data Uploaded</p>
            <p className="text-sm">Upload a CSV or JSON file to unlock insights</p>
        </div>
      )}

      {/* Dashboard Content */}
      {data && !loading && (
        <div className="space-y-6 md:space-y-8">
            {/* KPI Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
                {data.kpis.map((kpi, idx) => (
                    <div key={idx} className="bg-white dark:bg-slate-900 p-6 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-800 hover:shadow-md transition-shadow">
                        <div className="flex justify-between items-start mb-2">
                            <p className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wide">{kpi.label}</p>
                            {kpi.trend && (
                                <span className={`flex items-center text-xs font-bold px-2 py-1 rounded-full ${
                                    kpi.trend === 'up' ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400' : 
                                    kpi.trend === 'down' ? 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400' : 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300'
                                }`}>
                                    {kpi.trend === 'up' ? <TrendingUp size={12} className="mr-1"/> : <TrendingDown size={12} className="mr-1"/>}
                                    {kpi.change}
                                </span>
                            )}
                        </div>
                        <h3 className="text-2xl md:text-3xl font-extrabold text-slate-900 dark:text-white">{kpi.value}</h3>
                    </div>
                ))}
            </div>
            
            {/* Full Data Table */}
            <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-800 overflow-hidden flex flex-col">
                <div className="p-6 border-b border-slate-100 dark:border-slate-800">
                    <h3 className="text-lg font-bold text-slate-900 dark:text-white">Full Dataset</h3>
                    <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">Click on any row to analyze that specific record.</p>
                </div>
                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse min-w-[800px]">
                        <thead className="bg-slate-50 dark:bg-slate-800/50">
                            <tr>
                                {headers.map((header, index) => (
                                    <th key={index} className="p-4 text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
                                        {header}
                                    </th>
                                ))}
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                            {parsedRows.map((row, rowIndex) => (
                                <tr 
                                    key={rowIndex}
                                    onClick={() => analyzeSingleRow(row)}
                                    className="cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors"
                                >
                                    {headers.map((header, colIndex) => (
                                        <td key={colIndex} className="p-4 text-sm text-slate-600 dark:text-slate-300">
                                            {String(row[header] || '')}
                                        </td>
                                    ))}
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
      )}
    </div>
  );
};

const BarChart2Icon = ({className}:{className?:string}) => (
    <svg className={className} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
);